#!/usr/bin/env bash
#
# NextHello Docker Setup Script
# ==============================
# Interactive setup wizard for deploying NextHello with Docker
#
# Usage:
#   ./docker-setup.sh          # Interactive setup
#   ./docker-setup.sh --check  # Check prerequisites
#   ./docker-setup.sh --start  # Start containers
#   ./docker-setup.sh --stop   # Stop containers
#   ./docker-setup.sh --logs   # View logs
#   ./docker-setup.sh --qr     # Show WhatsApp QR code

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Symbols
CHECK="${GREEN}✓${NC}"
CROSS="${RED}✗${NC}"
ARROW="${CYAN}→${NC}"

print_banner() {
    echo ""
    echo -e "${CYAN}"
    echo "  _   _           _   _   _      _ _       "
    echo " | \ | | _____  _| |_| | | | ___| | | ___  "
    echo " |  \| |/ _ \ \/ / __| |_| |/ _ \ | |/ _ \ "
    echo " | |\  |  __/>  <| |_|  _  |  __/ | | (_) |"
    echo " |_| \_|\___/_/\_\\__|_| |_|\___|_|_|\___/ "
    echo -e "${NC}"
    echo -e " ${YELLOW}AI-Powered Networking Assistant${NC}"
    echo ""
}

check_command() {
    if command -v "$1" &> /dev/null; then
        echo -e "  ${CHECK} $1"
        return 0
    else
        echo -e "  ${CROSS} $1 (not found)"
        return 1
    fi
}

check_prerequisites() {
    echo -e "\n${BLUE}Checking prerequisites...${NC}\n"

    local all_good=true

    check_command "docker" || all_good=false
    check_command "docker-compose" || check_command "docker compose" || all_good=false

    # Check Docker daemon
    if docker info &> /dev/null; then
        echo -e "  ${CHECK} Docker daemon running"
    else
        echo -e "  ${CROSS} Docker daemon not running"
        all_good=false
    fi

    echo ""

    if [ "$all_good" = true ]; then
        echo -e "${GREEN}All prerequisites met!${NC}"
        return 0
    else
        echo -e "${RED}Some prerequisites are missing. Please install them first.${NC}"
        return 1
    fi
}

create_env_file() {
    if [ -f ".env" ]; then
        echo -e "\n${YELLOW}Found existing .env file.${NC}"
        read -p "Overwrite? (y/N): " overwrite
        if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
            echo "Keeping existing .env file."
            return
        fi
    fi

    echo -e "\n${BLUE}Creating .env file...${NC}\n"

    # Required
    echo -e "${ARROW} ${CYAN}Supabase Configuration${NC} (required)"
    read -p "  SUPABASE_URL: " SUPABASE_URL
    read -p "  SUPABASE_KEY: " SUPABASE_KEY

    # AI Provider
    echo -e "\n${ARROW} ${CYAN}AI Provider${NC} (at least one required)"
    read -p "  OPENAI_API_KEY (optional): " OPENAI_API_KEY
    read -p "  ANTHROPIC_API_KEY (optional): " ANTHROPIC_API_KEY

    # Integrations
    echo -e "\n${ARROW} ${CYAN}Integrations${NC} (optional but recommended)"
    read -p "  HEYGEN_API_KEY: " HEYGEN_API_KEY
    read -p "  CALENDLY_API_KEY: " CALENDLY_API_KEY
    read -p "  PROXYCURL_API_KEY: " PROXYCURL_API_KEY
    read -p "  HUBSPOT_API_KEY: " HUBSPOT_API_KEY
    read -p "  SENDGRID_API_KEY: " SENDGRID_API_KEY

    # App Config
    echo -e "\n${ARROW} ${CYAN}App Configuration${NC}"
    read -p "  Your Name: " NEXTHELLO_OWNER_NAME
    read -p "  Event Name (e.g., 'AI Summit 2024'): " NEXTHELLO_EVENT_NAME
    read -p "  Calendly Link (e.g., 'https://calendly.com/you'): " NEXTHELLO_CALENDLY_LINK

    # Generate webhook secret
    WEBHOOK_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p | tr -d '\n')

    # Write .env file
    cat > .env << EOF
# NextHello Configuration
# Generated by docker-setup.sh on $(date)

# ===========================================
# Database (Required)
# ===========================================
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_KEY=${SUPABASE_KEY}

# ===========================================
# AI Providers (At least one required)
# ===========================================
OPENAI_API_KEY=${OPENAI_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# ===========================================
# Integrations (Optional)
# ===========================================
HEYGEN_API_KEY=${HEYGEN_API_KEY}
CALENDLY_API_KEY=${CALENDLY_API_KEY}
PROXYCURL_API_KEY=${PROXYCURL_API_KEY}
HUBSPOT_API_KEY=${HUBSPOT_API_KEY}
SENDGRID_API_KEY=${SENDGRID_API_KEY}

# ===========================================
# App Configuration
# ===========================================
NEXTHELLO_OWNER_NAME=${NEXTHELLO_OWNER_NAME}
NEXTHELLO_EVENT_NAME=${NEXTHELLO_EVENT_NAME}
NEXTHELLO_CALENDLY_LINK=${NEXTHELLO_CALENDLY_LINK}

# ===========================================
# Docker Configuration
# ===========================================
NEXTHELLO_PORT=3000
NEXTHELLO_IMAGE=nexthello:local

# Webhook signature verification
WEBHOOK_SECRET=${WEBHOOK_SECRET}
EOF

    echo -e "\n${GREEN}Created .env file!${NC}"
    echo -e "${YELLOW}Webhook Secret: ${WEBHOOK_SECRET}${NC}"
    echo -e "Use this secret when configuring webhooks in HeyGen/Calendly."
}

create_config_file() {
    if [ -f "nexthello.config.json" ]; then
        echo -e "${YELLOW}Found existing nexthello.config.json${NC}"
        return
    fi

    echo -e "\n${BLUE}Creating nexthello.config.json...${NC}"

    # Read values from .env safely (handles spaces in values)
    if [ -f ".env" ]; then
        NEXTHELLO_EVENT_NAME=$(grep -E '^NEXTHELLO_EVENT_NAME=' .env | cut -d'=' -f2-)
        NEXTHELLO_OWNER_NAME=$(grep -E '^NEXTHELLO_OWNER_NAME=' .env | cut -d'=' -f2-)
        NEXTHELLO_CALENDLY_LINK=$(grep -E '^NEXTHELLO_CALENDLY_LINK=' .env | cut -d'=' -f2-)
    fi

    cat > nexthello.config.json << EOF
{
  "enabled": true,
  "eventName": "${NEXTHELLO_EVENT_NAME:-Conference 2024}",
  "ownerName": "${NEXTHELLO_OWNER_NAME:-Your Name}",
  "requiredFields": ["email", "company_name", "job_title"],

  "heygen": {
    "avatarId": "YOUR_AVATAR_ID",
    "voiceId": "YOUR_VOICE_ID"
  },

  "calendly": {
    "schedulingLink": "${NEXTHELLO_CALENDLY_LINK:-https://calendly.com/your-link}"
  },

  "crm": {
    "provider": "hubspot"
  },

  "messages": {
    "welcome": "Hey! Great meeting you at {{eventName}}! Here's a quick video from me:",
    "collectEmail": "What's your email? I'll send over some resources we discussed.",
    "collectCompany": "And which company are you with?",
    "collectTitle": "What's your role there?",
    "complete": "Perfect! Looking forward to connecting more. Feel free to book a time to chat!"
  }
}
EOF

    echo -e "${GREEN}Created nexthello.config.json!${NC}"
    echo -e "${YELLOW}Don't forget to update your HeyGen avatar/voice IDs.${NC}"
}

build_image() {
    echo -e "\n${BLUE}Building Docker image...${NC}\n"
    docker compose build
    echo -e "\n${GREEN}Build complete!${NC}"
}

start_containers() {
    echo -e "\n${BLUE}Starting NextHello...${NC}\n"
    docker compose up -d

    echo -e "\n${GREEN}NextHello is starting!${NC}"
    echo ""
    echo -e "${ARROW} View logs:        ${CYAN}docker compose logs -f${NC}"
    echo -e "${ARROW} WhatsApp QR:      ${CYAN}./docker-setup.sh --qr${NC}"
    echo -e "${ARROW} Stop:             ${CYAN}docker compose down${NC}"
    echo ""
    echo -e "${YELLOW}Webhook endpoints:${NC}"
    echo -e "  HeyGen:   http://your-domain:3000/webhooks/heygen"
    echo -e "  Calendly: http://your-domain:3000/webhooks/calendly"
}

stop_containers() {
    echo -e "\n${BLUE}Stopping NextHello...${NC}\n"
    docker compose down
    echo -e "${GREEN}Stopped.${NC}"
}

show_logs() {
    docker compose logs -f nexthello
}

show_qr() {
    echo -e "\n${BLUE}Looking for WhatsApp QR code...${NC}\n"
    echo -e "${YELLOW}Scan this QR code with WhatsApp:${NC}"
    echo -e "${YELLOW}(Settings → Linked Devices → Link a Device)${NC}\n"

    docker compose logs nexthello 2>&1 | grep -A 50 "QR Code" | head -60

    echo ""
    echo -e "${ARROW} If no QR appears, the session may already be authenticated."
    echo -e "${ARROW} To re-authenticate, delete the auth volume:"
    echo -e "   ${CYAN}docker volume rm nexthello-auth${NC}"
}

run_wizard() {
    print_banner

    echo -e "${BLUE}Welcome to NextHello Docker Setup!${NC}"
    echo "This wizard will help you configure and deploy NextHello."
    echo ""

    # Check prerequisites
    if ! check_prerequisites; then
        exit 1
    fi

    # Create .env
    create_env_file

    # Create config
    create_config_file

    # Build
    echo ""
    read -p "Build Docker image now? (Y/n): " do_build
    if [[ ! "$do_build" =~ ^[Nn]$ ]]; then
        build_image
    fi

    # Start
    echo ""
    read -p "Start NextHello now? (Y/n): " do_start
    if [[ ! "$do_start" =~ ^[Nn]$ ]]; then
        start_containers
    fi

    echo ""
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}  Setup complete! NextHello is ready to network.${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

# Main
case "${1:-}" in
    --check)
        check_prerequisites
        ;;
    --start)
        start_containers
        ;;
    --stop)
        stop_containers
        ;;
    --logs)
        show_logs
        ;;
    --qr)
        show_qr
        ;;
    --build)
        build_image
        ;;
    --help|-h)
        echo "NextHello Docker Setup"
        echo ""
        echo "Usage: ./docker-setup.sh [option]"
        echo ""
        echo "Options:"
        echo "  (none)    Interactive setup wizard"
        echo "  --check   Check prerequisites"
        echo "  --build   Build Docker image"
        echo "  --start   Start containers"
        echo "  --stop    Stop containers"
        echo "  --logs    View logs"
        echo "  --qr      Show WhatsApp QR code"
        echo "  --help    Show this help"
        ;;
    *)
        run_wizard
        ;;
esac