#!/usr/bin/env node
/**
 * Test script to generate and send a voice message using ElevenLabs
 *
 * Usage:
 *   # Generate and queue voice message
 *   ELEVENLABS_API_KEY=xxx node scripts/test-voice.mjs
 *
 *   # Just generate (don't send)
 *   ELEVENLABS_API_KEY=xxx node scripts/test-voice.mjs --generate-only
 *
 *   # Send existing file
 *   node scripts/test-voice.mjs --send-only /path/to/file.mp3
 */
import { writeFile, mkdir } from "fs/promises";
import { join } from "path";

const PHONE_NUMBER = process.argv[3] || "17544220907";
const RECIPIENT_NAME = "friend";

const config = {
  voiceId: "BMKogJVvmqzDZBd0Nwwq",
  modelId: "eleven_monolingual_v1",
  stability: 0.5,
  similarityBoost: 0.75,
};

const script = `Hey there! This is a test voice message generated by ElevenLabs.
I'm Michael's AI assistant, and I wanted to show you how we can send personalized voice notes.
Pretty cool, right? Let me know what you think!`;

async function generateVoice() {
  const { generateVoiceMessage } = await import("../dist/src/integrations/elevenlabs/client.js");

  console.log("Generating voice message...");
  console.log(`Phone: ${PHONE_NUMBER}`);
  console.log(`Script: ${script}`);
  console.log(`Voice ID: ${config.voiceId}`);

  const result = await generateVoiceMessage(config, script, RECIPIENT_NAME);

  if (result.status !== "completed" || !result.audioData) {
    console.error("Failed to generate voice:", result.error);
    process.exit(1);
  }

  console.log(`Generated ${result.audioData.length} bytes of audio`);

  // Save the audio file
  const mediaDir = "./data/media/voice";
  await mkdir(mediaDir, { recursive: true });

  const timestamp = Date.now();
  const filename = `voice_${PHONE_NUMBER}_${timestamp}.mp3`;
  const audioPath = join(mediaDir, filename);

  await writeFile(audioPath, result.audioData);
  console.log(`Saved to: ${audioPath}`);

  return audioPath;
}

async function sendVoice(audioPath) {
  const { addJob } = await import("../dist/src/queue/client.js");
  const { createCorrelationId } = await import("../dist/src/observability/logger.js");

  // Convert to container path if it's a local path
  const containerPath = audioPath.startsWith("/app/")
    ? audioPath
    : audioPath.replace(/^\.?\//, "/app/");

  console.log("\nQueueing voice message...");
  console.log(`Container path: ${containerPath}`);
  console.log(`NOTE: File must exist in the Docker container at this path`);
  console.log(`Copy with: docker cp ${audioPath} nexthello-whatsapp:${containerPath}`);

  const job = await addJob("outbound-messages", {
    correlationId: createCorrelationId(),
    phoneNumber: PHONE_NUMBER,
    channel: "whatsapp",
    messageType: "voice",
    content: containerPath,
    metadata: {
      generatedAt: new Date().toISOString(),
      test: true,
    },
  });

  if (job) {
    console.log(`Job queued: ${job.id}`);
  } else {
    console.log("Redis not available - cannot queue job");
  }
}

async function main() {
  const args = process.argv.slice(2);

  if (args.includes("--send-only")) {
    const filePath = args[args.indexOf("--send-only") + 1];
    if (!filePath) {
      console.error("Usage: --send-only /path/to/file.mp3");
      process.exit(1);
    }
    await sendVoice(filePath);
  } else if (args.includes("--generate-only")) {
    await generateVoice();
  } else {
    const audioPath = await generateVoice();
    await sendVoice(audioPath);
  }

  // Give Redis a moment to process
  setTimeout(() => process.exit(0), 2000);
}

main().catch(console.error);
